version: "3"
services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    hostname: unbound
    expose:
      - 53
    volumes:
      - ./volumes/unbound:/opt/unbound/etc/unbound/
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.7
    cap_add:
      - NET_ADMIN
    env_file: ./.env_pihole
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        
  wireguard:
    depends_on:
      - unbound
      - pihole
    image: linuxserver/wireguard:latest
    container_name: wireguard
    expose:
      - 5000
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ./volumes/wireguard/config:/config
      - /lib/modules:/lib/modules
    env_file: ./.env_administration
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    expose:
      - 9443
      - 8000
    depends_on:
      - wireguard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer_data:/data
    restart: always
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.4
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    volumes:
      - ./volumes/wire_ui_data:/app/db
      - ./volumes/wireguard/config:/etc/wireguard/
    env_file: ./.env_administration
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        
  pihole:
    depends_on:
      - unbound
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    expose:
     - 53
     - 67 # Se DHCP
     - 80
     - 22
     - 443
    dns:
      - 127.0.0.1
      - 100.100.100.7
    volumes:
      - ./volumes/pihole_data:/etc/pihole:rw
      #- ./volumes/pihole_dnsmasq_data/dnsmasq:/etc/dnsmasq.d:z  
      #- ./volumes/pihole_dnsmasq_data/custom_network.conf:/etc/dnsmasq.d/02-network.conf:ro    
      - ./volumes/pihole_custom_list/custom.list:/etc/pihole/custom.list   
    cap_add:
      - NET_ADMIN
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.5
    env_file: ./.env_pihole
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        
networks:
  administration-subnet:
    driver: bridge
    name: administration-subnet
    ipam:
      config:
        - subnet: "100.100.100.0/24"
          gateway: "100.100.100.1"
