version: '3.8'
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server-dev
    volumes:
      - ./volumes/code_data:/home/coder
    expose:
      - 8443
    networks:
      administration-net:
        ipv4_address: 100.100.100.30
    env_file: ./.env_devops
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        
        
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-dev
    user: root
    expose:
      - 8080 # Porta UI di Jenkins
      - 50000 # Porta agente Jenkins
    volumes:
      - ./volumes/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Permette a Jenkins di eseguire Docker
    networks:
      administration-net:
        ipv4_address: 100.100.100.31

networks:
  administration-net:
    external: true
    name: administration-subnet

