version: "3"
services:
  grafana-influxdb:
    image: influxdb:2.7
    container_name: influxdb
    expose:
      - 8086
    volumes:
      - ./volumes/grafana_influxdb:/var/lib/influxdb
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.20
    env_file: ./.env_monitoring
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472:472"
    expose:
      - 3000
    volumes:
      - ./volumes/grafana_data:/var/lib/grafana
      - ./volumes/grafana_dashboard/dashboards_files:/dashboards
      - ./volumes/grafana_dashboard/dashboard_conf:/etc/grafana/provisioning/dashboards
      - ./volumes/grafana_datasources:/etc/grafana/provisioning/datasources       
    dns:
      - 127.0.0.11
      - 100.100.100.5 
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.21
    env_file: ./.env_monitoring
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  loki:
    image: grafana/loki:latest
    expose:
      - 3100
    volumes:
      - ./volumes/loki_data:/tmp/loki
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.28        
        
  promtail:
    image: grafana/promtail:latest
    expose:
      - 9080
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./volumes/promtail_config/promtail_config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    logging:
      options:
        max-size: "10m"
        max-file: "3"    
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.29    
             
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    expose:
      - 9273
    volumes:
      - ./volumes/telegraf_config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      INFLUXDB_URI: "http://grafana-influx:8086"
    dns:
      - 127.0.0.11
      - 100.100.100.5
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.22
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    container_name: prometheus
    volumes:
     - ./volumes/prometheus_config/prometheus.yml:/etc/prometheus/prometheus.yml
     - ./volumes/prometheus_config/alert_rules.yml:/etc/prometheus/alert_rules.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    expose:
     - 9090 
    dns:
      - 127.0.0.11
      - 100.100.100.5
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.23
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    expose:
      - 9093
    dns:
      - 127.0.0.11
      - 100.100.100.5
    volumes:
      - ./volumes/alertmanager/data:/etc/alertmanager
      - ./volumes/alertmanager/alertmanager.yml:/etc/alertmanager/config.yml
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'  
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.24
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mailhog:
    image: mailhog/mailhog:latest
    expose:
      - 1025
      - 8025 
    dns:
      - 127.0.0.11
      - 100.100.100.5
    volumes:
      - ./volumes/maildir:/maildir
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.25
    env_file: ./.env_monitoring
    logging:
      options:
        max-size: "10m"
        max-file: "3"
                
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/kmsg:/dev/kmsg:ro
    expose:
      - 8080
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.26
    logging:
      options:
        max-size: "10m"
        max-file: "3"
               
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    expose:
      - 9100
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.27
    logging:
      options:
        max-size: "10m"
        max-file: "3"
#volumes:
#  grafana_data:  
                          
networks:
  administration-subnet:
    external: true
    name: administration-subnet