
version: "3"
services:

  ollama:
    volumes:
      - ./volumes/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    expose:
      - 11434
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.20
        
  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    volumes:
      - ./volumes/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    expose:
      - 8080
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
      - 'WEBUI_SECRET_KEY=aqzaq12wsxcde34rfvbgt56yhnmjy67uk'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      administration-subnet:
        ipv4_address: 100.100.100.21
        
networks:
  administration-subnet:
    external: true
    name: administration-subnet